### ISSUE TITLE
Where to ask questions regarding implementation details?

### ISSUE THREAD

**Issue by JesseRMeyer** [vblanco20-1/vulkan-guide#76]
Hi,

Thanks for the guide.  I have a question regarding how the depth culling logic works and do not know where to ask.

https://github.com/vblanco20-1/vulkan-guide/blob/164c144c4819840a9e59cc955a91b74abea4bd6f/shaders/indirect_cull.comp#L151

The current logic seems to only draw objects that are closer to the camera than other objects drawn the previous frame.  The article mentions "one frame of latency" but never explains how this resolves the following question.  Suppose that an object very close to the camera is drawn on frame N, but disappears the next frame.  Its depth values seem to always persist in the depth attachment, even after it is removed.  How is this artifact resolved?

zeux's depth culling technique uses some crafty logic to address this, that I have yet to locate something similar in this project:
https://github.com/zeux/niagara/blob/2fe8f9dd6477be4cad0df26a6e3162ac5593ce42/src/niagara.cpp#L1086-L1099

I'm working on building the engine locally to step through with RenderDoc but there's quite a few (undocumented) steps involved.

Thanks,
Jesse

**Comment by vblanco20-1** [comment]
The culling and indirect chapter is based on Zeux niagara repo, you can more or less see that the shaders are similar. I recomend you have a look at his youtube series where he builds that codebase from scratch and explains all of the logic with culling and indirect draw.

The issues with the one frame of latency is that in the case you comment, the object will just not be rendered. This is similar to what happens with unreal engine 4, where the engine makes the AABBs for culling a bit bigger to avoid too much flickering when turning a corner. One can use dual pass culling (cull once, build pyramid, cull again) to completely remove flickers and visual errors, which is what Nanite in ue5 does. But that scheme is harder to implement so it wasnt done in here. 

The engine branch of this project is not meant to be run locally, just to act as a reference to the extra chapter of the guide. Its missing the assets required to draw whole scenes due to licensing issues.
